import React from 'react';
import { Info, Globe, BarChart3, Leaf } from 'lucide-react';

const About: React.FC = () => {
  return (
    <div>
      <div className="flex items-center mb-6">
        <Info className="h-8 w-8 text-green-500 mr-2" />
        <h2 className="text-2xl font-bold text-gray-800">About the Carbon Footprint Calculator</h2>
      </div>
      
      <div className="bg-white p-6 rounded-lg shadow-md mb-8">
        <h3 className="text-xl font-semibold mb-4 text-gray-800">What is a Carbon Footprint?</h3>
        <p className="text-gray-700 mb-4">
          A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) 
          that are generated by our actions. The average global carbon footprint is about 4 tons per person per year, 
          but this varies significantly by country, lifestyle, and individual choices.
        </p>
        <div className="flex items-center justify-center my-6">
          <img 
            src="https://images.unsplash.com/photo-1569163139599-0f4517e36f31?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80" 
            alt="Carbon footprint concept" 
            className="rounded-lg max-w-full h-auto shadow-md"
          />
        </div>
        <p className="text-gray-700">
          Understanding your carbon footprint is the first step toward making more sustainable choices 
          and reducing your impact on climate change.
        </p>
      </div>
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
        <div className="bg-white p-6 rounded-lg shadow-md">
          <div className="flex items-center mb-4">
            <Globe className="h-6 w-6 text-green-500 mr-2" />
            <h3 className="text-xl font-semibold text-gray-800">Why It Matters</h3>
          </div>
          <p className="text-gray-700 mb-4">
            The global annual carbon footprint exceeds 40 billion tons, contributing significantly to climate change. 
            Climate change leads to:
          </p>
          <ul className="space-y-2 text-gray-700">
            <li className="flex items-start">
              <span className="text-green-500 mr-2">•</span>
              <span>Rising global temperatures</span>
            </li>
            <li className="flex items-start">
              <span className="text-green-500 mr-2">•</span>
              <span>More frequent and severe weather events</span>
            </li>
            <li className="flex items-start">
              <span className="text-green-500 mr-2">•</span>
              <span>Rising sea levels</span>
            </li>
            <li className="flex items-start">
              <span className="text-green-500 mr-2">•</span>
              <span>Threats to biodiversity and ecosystems</span>
            </li>
            <li className="flex items-start">
              <span className="text-green-500 mr-2">•</span>
              <span>Food and water security challenges</span>
            </li>
          </ul>
        </div>
        
        <div className="bg-white p-6 rounded-lg shadow-md">
          <div className="flex items-center mb-4">
            <BarChart3 className="h-6 w-6 text-green-500 mr-2" />
            <h3 className="text-xl font-semibold text-gray-800">How We Calculate</h3>
          </div>
          <p className="text-gray-700 mb-4">
            Our calculator estimates your carbon footprint based on your inputs in four main categories:
          </p>
          <ul className="space-y-2 text-gray-700">
            <li className="flex items-start">
              <span className="text-green-500 mr-2">•</span>
              <span><strong>Home Energy:</strong> Electricity, heating, and cooling</span>
            </li>
            <li className="flex items-start">
              <span className="text-green-500 mr-2">•</span>
              <span><strong>Transportation:</strong> Car travel, public transit, and flights</span>
            </li>
            <li className="flex items-start">
              <span className="text-green-500 mr-2">•</span>
              <span><strong>Food:</strong> Diet choices and consumption patterns</span>
            </li>
            <li className="flex items-start">
              <span className="text-green-500 mr-2">•</span>
              <span><strong>Consumption:</strong> Goods and services purchased</span>
            </li>
          </ul>
          <p className="text-gray-700 mt-4">
            We use emission factors from reputable sources to convert your activities into carbon dioxide 
            equivalent (CO₂e) emissions.
          </p>
        </div>
      </div>
      
      <div className="bg-green-50 p-6 rounded-lg">
        <div className="flex items-center mb-4">
          <Leaf className="h-6 w-6 text-green-500 mr-2" />
          <h3 className="text-xl font-semibold text-gray-800">Our Mission</h3>
        </div>
        <p className="text-gray-700 mb-6">
          We believe that individual actions, when multiplied by millions, can make a significant difference 
          in addressing climate change. Our mission is to:
        </p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="bg-white p-4 rounded-md shadow-sm">
            <h4 className="font-semibold text-gray-800 mb-2">Educate</h4>
            <p className="text-gray-700">
              Help people understand their environmental impact and the factors that contribute to it.
            </p>
          </div>
          <div className="bg-white p-4 rounded-md shadow-sm">
            <h4 className="font-semibold text-gray-800 mb-2">Empower</h4>
            <p className="text-gray-700">
              Provide actionable recommendations for reducing carbon footprints in everyday life.
            </p>
          </div>
          <div className="bg-white p-4 rounded-md shadow-sm">
            <h4 className="font-semibold text-gray-800 mb-2">Inspire</h4>
            <p className="text-gray-700">
              Motivate positive change through awareness and accessible sustainability practices.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default About;